# Generated by Django 5.0 on 2023-12-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('pizza_name', models.CharField(max_length=10)),
                ('pizza_desc', models.CharField(max_length=10)),
                ('pizza_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
